apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: dom-nginx
    image: nginx:latest
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
