apiVersion: v1
kind: Pod
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  containers:
    - name: counter
      image: lrakai/microservices:counter-v1
      env:
        - name: API_URL
          value: http://app-tier.service-discovery:8080
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"

    - name: poller
      image: lrakai/microservices:poller-v1
      env:
        - name: API_URL
          value: http://app-tier:$(APP_TIER_SERVICE_PORT)
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
